name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  CLABot:
    if: github.event_name == 'pull_request_target' || contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Signature Bot"
        uses: MetaMask/cla-signature-bot@v3.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'cla.json'
          url-to-cladocument: 'https://aips.ab.org/cla'
          branch: 'cla-signatures'
          allow-organization-members: false
          blockchain-storage-flag: false
