name: Deploy Github Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Wait on production-test
        uses: lewagon/wait-on-check-action@v0.1
        with:
          ref: main # can be commit SHA or tag too
          check-name: production-test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30 # seconds
      
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: Build
        working-directory: ./.web
        run: hugo --minify

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.web/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
